### ISSUE TITLE
Not a valid plugin name

### ISSUE THREAD

**Issue by cpantel** [dokufreaks/plugin-comment#11]
Hi, 

I know that the plugin says that it is compatible since 2014-05-05 "Ponder Stibbons" and we have  2013-05-10a "Weatherwax".

We are planning to upgrade soon, but maybe its only a very very little fix for that:

Message one (instalado exitosamente. -> succesfully installed)
Plugin (2 plugin(s): pax_global_header,dokufreaks-plugin-comment-0db44b5) instalado exitosamente.

Message two
Plugin name 'dokufreaks-plugin-comment-0db44b5' is not a valid plugin name, only the characters a-z and 0-9 are allowed. Maybe the plugin has been installed in the wrong directory?

Thank you

**Comment by splitbrain** [comment]
your wiki is too old.
