### ISSUE TITLE
Comment inside data entry does not work

### ISSUE THREAD

**Issue by nerdoc** [dokufreaks/plugin-comment#9]
Install the data plugin (https://www.dokuwiki.org/plugin:data), and create a page with a dataentry (I have something like this in a namespace template):

```
---- dataentry testentry ----
description: /* this comment here is visible!! */
----
/* this comment is ok */
```

The comments within this entry are shown as normal text. Maybe this is no real comments plugin bug, as it never gets to parse the entries - but maybe it should parse it BEFORE the data plugin (plugin order?)
Oh, besides that, GREAT plugin. Should be in dokuwiki core.

**Comment by tmo26** [comment]
From: https://www.dokuwiki.org/plugin:data#data_entry_input

"You may use the # character to add comments to the block. Those will be ignored and will neither be displayed nor saved."

If you want to add a comment to a dataentry:
```
---- dataentry testentry ----
description: # this comment is invisible!
----
```

If you want to hide the complete dataentry:

```
/*
---- dataentry testentry ----
description: # this complete dataentry is invisible!
----
*/
```

**Comment by LarsGit223** [comment]
@nerdoc: this seems to be answered/solved. If not, please re-open.

**Comment by nerdoc** [comment]
Yes, thanks!
